name: apptest
description: Retain your existing Flutter code, and use Dartive to make it faster.
version: 0.1.3
homepage: "https://dartive.dev"
repository: "https://github.com/justrach/dartive"
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.2
  dartive: ^0.1.3
  mime: ^1.0.2
  mongo_dart: ^0.9.1

dev_dependencies:
  test: any
  http: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec